username = "qh_rw"
password = "BEPQf67s"
host = "dds-2zefd5cd204049441717-pub.mongodb.rds.aliyuncs.com/qh_area_forecast"
port = 3717
uri = "mongodb://{}:{}@{}".format(username, password, host)
people_num_database = 'hist_loc_unum'
poi_database = 'XiAn_poi'
join_database = 'people_num_join_poi'
arima_database = 'arima_model_result'
